FROM tensorflow/tensorflow:2.0.0b1-gpu-py3-jupyter

RUN apt-get update && \
	apt-get install -y vim wget tmux

# Installing nodejs required for jupyterlab plugins
RUN wget https://deb.nodesource.com/setup_11.x
RUN chmod +x setup_11.x
RUN bash setup_11.x
RUN apt-get install -y nodejs

# Installing required packages (some are already present in tensorflow distribution)
RUN pip install --upgrade \
		request \
		scikit-image \
		scikit-learn \
		seaborn \
		tensorflow-probability \
		jupyterlab \
		ipywidgets \
		jupyter-tensorboard

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyterlab_tensorboard 

WORKDIR /tf
